name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17
            # credentials:
            #     username: aliu12
            #     password: password
            env:
                API_URL: some_url.com
            ports:
                - 80
            # voluemes:
            #     - vol_name:/path/in/container
            #     - /path/to/container
            #     - /path/in/host:/path/in/container
            # options: --cpus 1
        steps:
            - name: Log Node & OS Versions
              run: |
               node -v
               cat /etc/os-release
            - name: Log Env
              run: echo $API_URL
            - name: Create File
              run: echo 'some text' > text.txt
            - name: COntainer in a step
              uses: docker://node:18.16-alpine3.17
              with:
                args: -p 2+3
            - name: Log Node Version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v 
            - name: show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt