name: Simple Action
on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Displayworking Directory and List files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: VIewing .github dir
              working-directory: /home/runner/work/learning/learning/.github/
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: viewing actions dir
              working-directory: /home/runner/work/learning/learning/.github/Actions
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: View hello-docker dir
              working-directory: /home/runner/work/learning/learning/.github/Actions/hello-docker
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Simple Docker action
              id: greet
              uses: ./.github/Actions/hello-docker
              with: 
                who-to-greet: Aaron
            - name: Log Greeting Time
              run: echo "${{ steps.greet.outputs.time }}"
            - name: Log ENV Var
              run: echo $HELLO_TIME